### ISSUE TITLE
Fastapi в качестве сервера

### ISSUE THREAD

**Issue by fortunto2** [fscdev/vkwave#101]
Крутой проект, обязательно попробую. 
Респект за pydantic очень его люблю и смотрю что написали очень много классов. Что очень удобно. 

А не думали Fastapi в качестве сервера? он тоже из коробки идет с pydantic

**Comment by prostomarkeloff** [comment]
- FastAPI не идёт вместе с Pydantic
- У нас уже есть aiohttp
