### ISSUE TITLE
Баг с загрузкой документов на сервера ВК

### ISSUE THREAD

**Issue by dadyarri** [fscdev/vkwave#112]
**TL;DR**
Если попытаться загрузить документ по урлу, кидается исключение
```
vkwave.bots.utils.uploaders.uploader.UploadException: bad_image
```
**Полный трейсбек:** uni-jacob/jacob#61

**Comment by kesha1225** [comment]
https://github.com/fscdev/vkwave/commit/327a9d5c61f3f75982f791c399a5b555a0f592e3 fixed!
