### ISSUE TITLE
ImportError: cannot import name 'BotEvent' from 'vkwave.bots' (C:\Python38\lib\site-packages\vkwave\bots\__init__.py)

### ISSUE THREAD

**Issue by A-Gear** [fscdev/vkwave#35]
При попытке запустить скрипт из примера выходит данная ошибка.
![image](https://user-images.githubusercontent.com/34795565/80627548-90936780-8a69-11ea-8b21-420cbdf79f59.png)
как это исправить?

Windows 10
Python 3.8

**Comment by A-Gear** [comment]
Использовал [этот](https://github.com/fscdev/vkwave/blob/master/examples/bots/chat_event_example.py) пример

**Comment by kesha1225** [comment]
Либу ставил с гитхаба?

**Comment by prostomarkeloff** [comment]
@kesha1225 test

**Comment by kesha1225** [comment]
> Использовал [этот](https://github.com/fscdev/vkwave/blob/master/examples/bots/chat_event_example.py) пример

https://github.com/fscdev/vkwave/blob/d709f9d9dc20f80eea2eb1de80636f3b7780fa11/vkwave/bots/__init__.py#L12 в версии на гитхабе импорт на месте, на пупи пока не обновлял
Стоит поставить библиотеку с гита:
```
pip install https://github.com/fscdev/vkwave/archive/master.zip
```

**Comment by A-Gear** [comment]
Помогло. Спасибо.
