### ISSUE TITLE
Мультиакк лонгполл

### ISSUE THREAD

**Issue by sergeyfilippov1** [fscdev/vkwave#43]
Как реализовать лонгполл на много аккаунтов?
Мне нужно чтобы одновременно работало несколько ботов

**Comment by prostomarkeloff** [comment]
Либо https://github.com/fscdev/vkwave/blob/master/examples/bots/clones_bot_example.py, либо несколько Extension-ов. 
А у вас какой бот? Юзер или группа?

**Comment by sergeyfilippov1** [comment]
Юзер

**Comment by prostomarkeloff** [comment]
> Юзер
https://github.com/fscdev/vkwave/blob/master/examples/bots/clones_bot_example.py должно подойти.
