### ISSUE TITLE
Что это такое, кто это сделал, а главное зачем?

### ISSUE THREAD

**Issue by lightmanLP** [fscdev/vkwave#51]
![image](https://user-images.githubusercontent.com/50497969/90483452-ec8c1400-e15e-11ea-874d-6095b1241efb.png)
vkwave/vkscript/execute.py
Для таких случаев существует __init__.

**Comment by prostomarkeloff** [comment]
Конвертер кода в VKScript, стащенный ещё из vk.py. Всегда готовы принять ваши PR =)
