### ISSUE TITLE
Добавить кеширование и тротлинг

### ISSUE THREAD

**Issue by peach-lasagna** [fscdev/vkwave#75]

**Comment by prostomarkeloff** [comment]
Поподробнее, пожалуйста.

**Comment by peach-lasagna** [comment]
https://github.com/PythonReforker/vk.py/tree/master/vk/bot_framework/addons/caching

**Comment by prostomarkeloff** [comment]
https://github.com/fscdev/vkwave/blob/master/vkwave/bots/addons/cache/cached_filter.py
