### ISSUE TITLE
повесить onstartup/onshutdown в simple bot

### ISSUE THREAD

**Issue by peach-lasagna** [fscdev/vkwave#76]

**Comment by peach-lasagna** [comment]
Сейчас оно выглядит так https://github.com/fscdev/vkwave/blob/a8dd8b7706bf12f3bb4201e1098872139a615d51/vkwave/bots/addons/easy/task_manager.py#L22

**Comment by kesha1225** [comment]
И нормально выглядит! Предлагаю закрыть ишью

**Comment by peach-lasagna** [comment]
@kesha1225 Нет

**Comment by vlalog** [comment]
стоп...
а что мешает использовать TaskManager?
![image](https://user-images.githubusercontent.com/56760680/95773812-dcf4fb80-0cc7-11eb-9404-01658effd9c8.png)
