### ISSUE TITLE
Добавить админку боту

### ISSUE THREAD

**Issue by peach-lasagna** [fscdev/vkwave#83]
То есть бот проверяет ид юзера и пр. И если это совпадает с данными об админе - предоставляет ему что-либо(например кнопки для просмотра логов/дебага/спец возможностей)

**Comment by prostomarkeloff** [comment]
Вынести в отдельную библиотеку.

**Comment by peach-lasagna** [comment]
@prostomarkeloff Зочем? 0_0

**Comment by peach-lasagna** [comment]
@prostomarkeloff @kesha1225 меня мархеров обижает
