### ISSUE TITLE
Добавить админку боту 

### ISSUE THREAD

**Issue by peach-lasagna** [fscdev/vkwave#84]
Бот проверяет ид юзера и пр. И если это совпадает с данными об админе - предоставляет ему доступ к панели админа.
Панель админа будет реализована паттерном MVC, что даст более гибкую структуру панели.
Сама панель будет состоять из кнопок или чего-то другого.

**Comment by peach-lasagna** [comment]
ишью не закрывать, сделаю у себя в форке, кто захочет - пусть присоединяется

**Comment by prostomarkeloff** [comment]
Реализация в отдельной библиотеке.
